# Generated by Django 5.2.8 on 2025-11-28 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('model_type', models.CharField(choices=[('yolov8n', 'YOLOv8 Nano'), ('yolov8s', 'YOLOv8 Small'), ('yolov8m', 'YOLOv8 Medium'), ('custom', 'Custom Model')], max_length=20)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ai_models/')),
                ('is_active', models.BooleanField(default=False)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('classes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_image', models.ImageField(upload_to='detection_inputs/')),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='detection_outputs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('model_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_integration.aimodel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('inference_speed', models.FloatField()),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_integration.aimodel')),
            ],
        ),
    ]
