# Generated by Django 5.2.8 on 2025-11-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='vehicle_type',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('tuktuk', 'Tuktuk'), ('bicycle', 'Bicycle'), ('animal_cart', 'Animal Cart'), ('car', 'Car'), ('truck', 'Truck'), ('bus', 'Bus')], max_length=20),
        ),
    ]
